### ISSUE TITLE
完全不明白作者想干嘛！

### ISSUE THREAD

**Issue by lvtao-net** [outman/dcode#2]
安装完后，按官方的样式可以输出二维码了，结果我传入的小写全变成了大写~~~很纠结呀

**Comment by outman** [comment]
是否是大小写跟最后一个参数有关系，方法是支持多个参数的，默认输出为大写（默认为0）。
`
<?php
 $filecontent = DCode::qrcode("HELLOhh", 0, 0, 3, 1);
 file_put_contents("test.png", $filecontent);
`

**Comment by outman** [comment]
@lvtao320 是否是大小写跟最后一个参数有关系，方法是支持多个参数的，默认输出为大写（默认为0）。
`<?php`
`$filecontent = DCode::qrcode("HELLOhh", 0, 0, 3, 1);`
`file_put_contents("test.png", $filecontent);`
